Bugfixes and necessary changes with updated server

diff --git a/timeout b/timeout
--- a/timeout
+++ b/timeout
@@ -1,34 +1,45 @@
 #!/bin/bash
 
+getPids() {
+    PGID=$(ps --pid $$ -o pgid --noheader)
+    USER=$(id -n -u)
+    PIDS=$(ps -u "$USER" -o pgid,pid --noheader)
+    echo "$PIDS" | grep "^$PGID " | awk -e '{print $2}'
+}
+
 TIMER="$1"
 shift
 
-# Disable monitor mode
-set +m
+# Enable monitor mode. Subshells are exected in their own process groups.
+set -m
 
-# The program to execute
 (
-    "$@"
-) &
-PROGRAM_PID=$!
+	PIDS=$(getPids)
 
-# The timer
-(
-    sleep $TIMER
-    kill "$PROGRAM_PID"
-) > /dev/null 2>&1 &
-TIMER_PID=$!
+	# Execute the program
+	"$@" &
+	PROGRAM_PID=$!
 
-# Delay until one of the processes finish.
-# Avoid "wait -n" because older bash doesn't support it
-# This also hides a "Terminated" message
-wait $PROGRAM_PID > /dev/null 2>&1
-RESULT=$?
+        # Set up the timer
+	(
+        	sleep "$TIMER"
+		TARGETS=$(getPids)
+		TARGETS=$(echo -e "$TARGETS\n$PIDS\n$PIDS" | sort | uniq -u)
+		kill -9 $TARGETS $$
+	) &
+	TIMER_PID=$!
 
-# Kill the timeout process if it isn't already killed
-kill $TIMER_PID > /dev/null 2>&1
+	# Delay until program finishes. This could happen normally or via the timeout.
+        # Avoid "wait -n" because older bash doesn't support it.
+        # This also hides a "Terminated" message
+        wait "$PROGRAM_PID" > /dev/null 2>&1
+        RESULT=$?
 
-# Clean up, hide the "Terminated" message, prevent bash from dying
-wait $TIMER_PID > /dev/null 2>&1
+        # Kill the timeout process if it isn't already killed
+        kill -9 "$TIMER_PID" > /dev/null 2>&1
 
-exit $RESULT
+        # Clean up, hide the "Terminated" message, prevent bash from dying
+        wait "$TIMER_PID" > /dev/null 2>&1
+
+        exit "$RESULT"
+)
